### PR TITLE
API-Setup-and-swagger.yaml-Docs

### PR DESCRIPTION
**Pull request by Zuwairanajma**
**In this branch i implemented the following**
- Created migrations and models for tutorials, user, and reservations.
- Created the controllers and APIs for tutorials and reservations
- Set the API route root to the tutorials
- Add the schema for the project.
- Created and updated the swagger.yaml file

### CODE REVIEW

**Review by RicardoEgas — APPROVED** [review]
Great job implementing the API documentation!

**Comment by mohammadnewton** [comment]
Hi @Zuwairanajma 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - Boiler-plated files removed :heavy_check_mark: 
 - Install necessary project dependencies :heavy_check_mark:
 - Set up Routes :heavy_check_mark:  
  

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @mohammadnewton

**Review by nejidevelops — APPROVED** [review]
Hi @Zuwairanajma 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - Boiler-plated files removed :heavy_check_mark: 
 - Install necessary project dependencies :heavy_check_mark:
 - Set up Routes :heavy_check_mark:  
  

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @mohammadnewton

**Review by AliRezaBmeDu — COMMENTED** [review]
Great work with the api documentation

**Pull request closed without merging**
